[platformio]
default_envs = esp32_a

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:esp32_a]
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
build_flags = -DNODE_A

[env:esp32_b]
upload_port = /dev/ttyUSB1
monitor_port = /dev/ttyUSB1
build_flags = -DNODE_B