[platformio]
default_envs = uno_alice, uno_bob

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/Ethernet@^2.0.2
build_flags =
    -std=gnu++11
    -Wall
    -Wextra

[env:uno_alice]
build_flags =
    ${env.build_flags}
    -DNODE_ROLE_ALICE=1

[env:uno_bob]
build_flags =
    ${env.build_flags}
    -DNODE_ROLE_BOB=1
